/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkers;

public class App {

    public static void main(String[] args) {
        CheckersBoard.initBoard().printBoard();
    }
}
