/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkers;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	@Test
	public void countPiecesTest() {
		CheckersBoard initBoard = CheckersBoard.initBoard();
		assertEquals(12, initBoard.countPiecesOfPlayer(CheckersBoard.Player.BLACK));
		assertEquals(12, initBoard.countPiecesOfPlayer(CheckersBoard.Player.RED));
	}
}
