/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package checkers;

import checkers.exception.BadMoveException;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	@Test
	public void countPiecesTest() {
		CheckersBoard initBoard = CheckersBoard.initBoard();
		assertEquals(12, initBoard.countPiecesOfPlayer(CheckersBoard.Player.BLACK));
		assertEquals(12, initBoard.countPiecesOfPlayer(CheckersBoard.Player.RED));
	}

	@Test
	public void moveTest() {
		CheckersBoard initBoard = CheckersBoard.initBoard();
		try {
			initBoard.processMove(CheckersMove.builder().fromPosition(2, 1).toPosition(3, 0).build());
		} catch (BadMoveException ex) {
			assertEquals("You must move YOUR pieces!", ex.getMessage());
		}
		try {
			initBoard.processMove(CheckersMove.builder().fromPosition(5, 0).toPosition(-1, 4).build());
		} catch (BadMoveException ex) {
			assertEquals("All coordinates must be between [0-7]!", ex.getMessage());
		}
		try {
			initBoard.processMove(CheckersMove.builder().fromPosition(6, 1).toPosition(5, 0).build());
		} catch (BadMoveException ex) {
			assertEquals("You can only move into empty spaces!", ex.getMessage());
		}
		try {
			initBoard.processMove(CheckersMove.builder().fromPosition(5, 2).toPosition(3, 4).build());
		} catch (BadMoveException ex) {
			assertEquals("You can only capture your opponent's pieces!", ex.getMessage());
		}
		try {
			initBoard.processMove(CheckersMove.builder().fromPosition(5, 0).toPosition(3, 6).build());
			fail("An invalid move was accepted!");
		} catch (BadMoveException ex) {
			assertEquals("You can only move 1 space away, or capture 2 spaces away!", ex.getMessage());
		}
	}

	@Test
	public void gameTest() {

	}
}
